[tool.poetry]
name = "ideal piano (for windows)"
version = "0.1.0"
description = ""
authors = ["GustavTheTrainee <gustavsvensson941@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

